# Generated by Django 5.2 on 2025-04-29 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), verbose_name='Duration'),
        ),
    ]
