# Generated by Django 5.2 on 2025-04-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='start',
            new_name='start_time',
        ),
    ]
