# Generated by Django 5.2 on 2025-05-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
