# Generated by Django 5.2 on 2025-05-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_appointment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meeting URL'),
        ),
    ]
